### ISSUE TITLE
Add support for hours and seconds inputs

### ISSUE THREAD

**Issue by Cazaimi** [Cazaimi/simpleMacTimer#2]
Currently, the program only supports adding a minute timer.

**Comment by vantezzen** [comment]
I'd like implement this.

How about a syntax like this:
```sh
bash timer 50min  # => 50 minutes
bash timer 15m 00s # => 15 minutes, 0 seconds
bash timer 0h 25sec # => 25 seconds
bash timer 1h # => 1 hour
bash timer 15h 14min 12sec # => 15 hours, 14 minutes, 12 seconds
bash timer 5 # => 5 minutes (to stay compatible with the current version)
```

**Comment by Cazaimi** [comment]
@vantezzen looks good. I assume you're suggesting support for both short and long tokens for time units?

Ex: `s`, `sec` `seconds` all achieve the same thing as long as they're appended to a number (without whitespace).

**Comment by Cazaimi** [comment]
Also, at this stage, we should limit the input to stay in bounds:

1. `0-59` for seconds

No bounds on hours (for obvious reasons) and no bound on minutes, only when it's provided as in the previous implementation.

**Comment by vantezzen** [comment]
Yes, my suggestion would be to add various synonyms and short tokens for units, just so you can write the time in whatever way you like - e.g.  keeping it as short as possible with `1h`, writing the full word like `hours` or `hour`. This allows you to use the script without having to look up the correct tokens you can use.

I would also suggest not limiting the input to be between 0 and 59. The reason for this is a situation like this: You run 3 processes serially that each run 30 minutes and you want to run a timer for this time. Some quick calculation says it will take 90 minutes, so you simply run `bash timer 90min`. 
The only improvement I see with limiting the input is that it could limit errors by typos, e.g. adding a 0 at the end by mistake but I don't think it is worth limiting the user's abilities to use the tool.

**Comment by Cazaimi** [comment]
I understand the use case that you mentioned. However:

1. I want these features developed incrementally and I feel this overflow feature deserves a ticket of its own. Like a function a ticket should target one thing and do it well.
2. The use case that you mentioned can be achieved by running `bash timer 90`, since we’re sticking with the previous implementation.
